# Generated by Django 2.0.7 on 2018-07-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128, verbose_name='任务ID')),
                ('first', models.IntegerField(verbose_name='第一个值')),
                ('second', models.IntegerField(verbose_name='第二个值')),
                ('log_date', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '相加',
                'verbose_name_plural': '相加',
            },
        ),
    ]
